# =========================
# LOCAL DATABASE
# =========================
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgresdb:5432/usermanagement}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin_macbook}

# =========================
# LOCAL JWT
# =========================
usermanagement:
  jwt:
    generate-ephemeral-key: ${JWT_GENERATE_EPHEMERAL_KEY:true}

# =========================
# LOCAL LOGGING
# =========================
sdk:
  logging:
    structured:
      enabled: true
      auto-configure-format: false

logging:
  structured:
    format:
      console: ""
